/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthOfficerRole;

import Business.Employee.Resident;
import Business.Sensor.AirSensor;
import Business.Sensor.AirSensorReading;
import Business.VitalSigns.PatientVitalSign;
import Business.VitalSigns.PatientVitalSignHistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanda
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    private JPanel userProcessContainer;
    private PatientVitalSignHistory vsh;
    private Resident resident;
    private AirSensorReading asr;
    public ViewPersonJPanel(JPanel userProcessContainer, Resident resident) {
        
        vsh = resident.getPatientVitalSignHistory();
        asr = resident.getAirSensorReading();
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.resident = resident;
        populateFields();
        populateTable();
        populateAirSensorTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fNTxt = new javax.swing.JTextField();
        phNumTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientVSTable = new javax.swing.JTable();
        deleteJButton = new javax.swing.JButton();
        viewDetailsJButton = new javax.swing.JButton();
        systolicBPTxt = new javax.swing.JTextField();
        weightTxt = new javax.swing.JTextField();
        heartRateTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        respRateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pIDTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pAgeTxt = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        requestTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        airSensorJTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        so2txt = new javax.swing.JTextField();
        carbon = new javax.swing.JLabel();
        coTxt = new javax.swing.JTextField();
        ozone = new javax.swing.JLabel();
        o3Txt = new javax.swing.JTextField();
        nitroTxt = new javax.swing.JLabel();
        no2Txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        viewDetailsJButton1 = new javax.swing.JButton();
        deleteJButton1 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Profile");

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Phone Number");

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Email address");

        emailTxt.setEditable(false);
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        jLabel13.setBackground(java.awt.Color.white);
        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Name");

        fNTxt.setEditable(false);
        fNTxt.setEnabled(false);
        fNTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNTxtActionPerformed(evt);
            }
        });

        phNumTxt.setEditable(false);

        patientVSTable.setFont(new java.awt.Font("Californian FB", 0, 11)); // NOI18N
        patientVSTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Vital Sign Report"
            }
        ));
        jScrollPane1.setViewportView(patientVSTable);

        deleteJButton.setBackground(java.awt.Color.white);
        deleteJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteJButton.setText("Delete");
        deleteJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteJButton.setContentAreaFilled(false);
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        viewDetailsJButton.setBackground(java.awt.Color.white);
        viewDetailsJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewDetailsJButton.setText("View Details");
        viewDetailsJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewDetailsJButton.setContentAreaFilled(false);
        viewDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButtonActionPerformed(evt);
            }
        });

        systolicBPTxt.setEditable(false);

        weightTxt.setEditable(false);

        heartRateTxt.setEditable(false);

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Respiratory Rate");

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Heart Rate");

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Weight");

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Systolic Blood Pressure");

        respRateTxt.setEditable(false);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Patient ID");

        pIDTxt.setEnabled(false);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Age");

        pAgeTxt.setEditable(false);

        backJButton.setBackground(java.awt.Color.white);
        backJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backJButton.setText("<<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.setContentAreaFilled(false);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Generate Graph");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(java.awt.Color.white);
        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setText("Request status");

        requestTxt.setEditable(false);

        airSensorJTable.setFont(new java.awt.Font("Californian FB", 0, 11)); // NOI18N
        airSensorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Air Sensor Reading"
            }
        ));
        jScrollPane2.setViewportView(airSensorJTable);

        jLabel16.setBackground(java.awt.Color.white);
        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setText("Sulphur dioxide");

        so2txt.setEditable(false);

        carbon.setBackground(java.awt.Color.white);
        carbon.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        carbon.setText("Carbon monoxide");

        coTxt.setEditable(false);

        ozone.setBackground(java.awt.Color.white);
        ozone.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ozone.setText("Ozone");

        o3Txt.setEditable(false);

        nitroTxt.setBackground(java.awt.Color.white);
        nitroTxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nitroTxt.setText("Nitrogen dioxide");

        no2Txt.setEditable(false);

        jLabel20.setBackground(java.awt.Color.white);
        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Request status");

        statusTxt.setEditable(false);

        viewDetailsJButton1.setBackground(java.awt.Color.white);
        viewDetailsJButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewDetailsJButton1.setText("View Details");
        viewDetailsJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewDetailsJButton1.setContentAreaFilled(false);
        viewDetailsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButton1ActionPerformed(evt);
            }
        });

        deleteJButton1.setBackground(java.awt.Color.white);
        deleteJButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteJButton1.setText("Delete");
        deleteJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteJButton1.setContentAreaFilled(false);
        deleteJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(viewDetailsJButton)
                            .addGap(60, 60, 60)
                            .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(514, 514, 514))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailTxt)
                                        .addComponent(fNTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pAgeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pIDTxt)
                                        .addComponent(phNumTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                                    .addGap(248, 248, 248))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(heartRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(respRateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(systolicBPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(requestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(153, 153, 153))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(391, 391, 391)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(nitroTxt))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(statusTxt)
                                                        .addComponent(no2Txt)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(carbon)
                                                        .addComponent(ozone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(coTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                                        .addComponent(o3Txt)))
                                                .addComponent(jLabel16)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(viewDetailsJButton1)
                                                    .addGap(55, 55, 55)
                                                    .addComponent(deleteJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(114, 114, 114)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(backJButton)
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(201, 201, 201)))
                                        .addGap(260, 260, 260))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(so2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(468, 468, 468)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteJButton)
                    .addComponent(viewDetailsJButton)
                    .addComponent(viewDetailsJButton1)
                    .addComponent(deleteJButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(respRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(heartRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(systolicBPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(so2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carbon)
                            .addComponent(coTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ozone)
                            .addComponent(o3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nitroTxt)
                            .addComponent(no2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(requestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backJButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void fNTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNTxtActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = patientVSTable.getSelectedRow();
        if(selectedRow >= 0){
            int dialogueButton = JOptionPane.YES_NO_OPTION;
            int dialogueResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the selected Vital Sign?", "Warning", dialogueButton);
            if (dialogueResult == JOptionPane.YES_OPTION){
                PatientVitalSign vs = (PatientVitalSign)patientVSTable.getValueAt(selectedRow, 0);
                vsh.deleteVitalSign(vs);
                populateTable();
                resetFields();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please select the row to be deleted","Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteJButtonActionPerformed

    public void populateFields(){
        fNTxt.setText(resident.getName());
        pIDTxt.setText(Integer.toString(resident.getpID()));
        emailTxt.setText(resident.getEmail());
        //areaTxt.setText(String.valueOf(resident.getAreaCode()));
        phNumTxt.setText(String.valueOf(resident.getPhNum()));
        pAgeTxt.setText(String.valueOf(resident.getAge()));
       
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) patientVSTable.getModel();
        dtm.setRowCount(0);

         for(PatientVitalSign p : resident.getPatientVitalSignHistory().getPatientVitalSignHistory()){
            Object row[] = new Object [2];
            row[0]= p;
            row[1]= p.getStatus();
            dtm.addRow(row);
        }
        
        
    }
    
    public void populateAirSensorTable(){
        DefaultTableModel dtm = (DefaultTableModel) airSensorJTable.getModel();
        dtm.setRowCount(0);

         for(AirSensor as : resident.getAirSensorReading().getAirSensorReading()){
            Object row[] = new Object [2];
            row[0]= as;
            row[1]= as.getAirQualityStatus();
            dtm.addRow(row);
        }
        
        
    }
    
    public void resetFields(){
        pIDTxt.setText("");
        pAgeTxt.setText("");
        respRateTxt.setText("");
        heartRateTxt.setText("");
        systolicBPTxt.setText("");
        weightTxt.setText("");
        so2txt.setText("");
        no2Txt.setText("");
        o3Txt.setText("");
        carbon.setText("");
    }
    
    private void viewDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = patientVSTable.getSelectedRow();
        //System.out.print("RowCount:" + selectedRow);
        if(selectedRow >= 0){
            PatientVitalSign vs = (PatientVitalSign)patientVSTable.getValueAt(selectedRow, 0);
            

            respRateTxt.setText(Float.toString(vs.getRespiratoryRate()));
            heartRateTxt.setText(Float.toString(vs.getHeartRate()));
            systolicBPTxt.setText(Float.toString(vs.getSystolicBP()));
            weightTxt.setText(Float.toString(vs.getWeight()));
            requestTxt.setText(vs.getVsRequest());
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the date for which details are to be retrieved", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);  //removes current panel from the stack
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChartGraphJPanel chartGraphJPanel = new ChartGraphJPanel(userProcessContainer,resident);
        userProcessContainer.add("chartGraphJPanel",chartGraphJPanel);  // string descp, panel which v r adding --ad to stack i.e userprocess container
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();  //typecasting the layout to card layout
        layout.next(userProcessContainer); //moving forward and pass the container
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewDetailsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = airSensorJTable.getSelectedRow();
        //System.out.print("RowCount:" + selectedRow);
        if(selectedRow >= 0){
            AirSensor as = (AirSensor)airSensorJTable.getValueAt(selectedRow, 0);
            so2txt.setText(Double.toString(as.getSulphurDiOxide()));
            coTxt.setText(Double.toString(as.getCarbonMonoOxide()));
            o3Txt.setText(Double.toString(as.getOzone()));
            no2Txt.setText(Double.toString(as.getNitrogenOxide()));
            statusTxt.setText(as.getAsRequest());
            //statusTxt.setText(as.get);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the date for which details are to be retrieved", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailsJButton1ActionPerformed

    private void deleteJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = airSensorJTable.getSelectedRow();
        if(selectedRow >= 0){
            int dialogueButton = JOptionPane.YES_NO_OPTION;
            int dialogueResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the selected Vital Sign?", "Warning", dialogueButton);
            if (dialogueResult == JOptionPane.YES_OPTION){
                AirSensor as = (AirSensor)airSensorJTable.getValueAt(selectedRow, 0);
                asr.deleteAirSensorReading(as);
                populateTable();
                resetFields();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please select the row to be deleted","Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airSensorJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel carbon;
    private javax.swing.JTextField coTxt;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton deleteJButton1;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fNTxt;
    private javax.swing.JTextField heartRateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nitroTxt;
    private javax.swing.JTextField no2Txt;
    private javax.swing.JTextField o3Txt;
    private javax.swing.JLabel ozone;
    private javax.swing.JTextField pAgeTxt;
    private javax.swing.JTextField pIDTxt;
    private javax.swing.JTable patientVSTable;
    private javax.swing.JTextField phNumTxt;
    private javax.swing.JTextField requestTxt;
    private javax.swing.JTextField respRateTxt;
    private javax.swing.JTextField so2txt;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JTextField systolicBPTxt;
    private javax.swing.JButton viewDetailsJButton;
    private javax.swing.JButton viewDetailsJButton1;
    private javax.swing.JTextField weightTxt;
    // End of variables declaration//GEN-END:variables
}
