/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MayorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.MayorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vanda
 */
public class MayorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MayorWorkAreaJPanel1
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    private MayorOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    
    public MayorWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account, MayorOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.organization = organization;
        this.enterprise = enterprise;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newRequestJButton = new javax.swing.JButton();
        manageFunds = new javax.swing.JButton();
        viewReportsJButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        newRequestJButton.setBackground(java.awt.Color.white);
        newRequestJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        newRequestJButton.setText("View New Requests");
        newRequestJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRequestJButtonActionPerformed(evt);
            }
        });

        manageFunds.setBackground(java.awt.Color.white);
        manageFunds.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        manageFunds.setText("Manage Funds");
        manageFunds.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        viewReportsJButton.setBackground(java.awt.Color.white);
        viewReportsJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewReportsJButton.setText("View City Reports");
        viewReportsJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newRequestJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageFunds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewReportsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(newRequestJButton)
                .addGap(49, 49, 49)
                .addComponent(viewReportsJButton)
                .addGap(52, 52, 52)
                .addComponent(manageFunds)
                .addGap(154, 154, 154))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRequestJButtonActionPerformed
        // TODO add your handling code here:
        ViewWorkRequestsJPanel viewWorkRequestsJPanel = new ViewWorkRequestsJPanel(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("viewWorkRequestsJPanel", viewWorkRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_newRequestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageFunds;
    private javax.swing.JButton newRequestJButton;
    private javax.swing.JButton viewReportsJButton;
    // End of variables declaration//GEN-END:variables
}
