/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EPASpecialistRole;

//import userinterface.MayorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EPAOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vanda
 */
public class EPAWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MayorWorkAreaJPanel1
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    private EPAOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    
    public EPAWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account, EPAOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.organization = organization;
        this.enterprise = enterprise;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newRequestJButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        newRequestJButton.setBackground(java.awt.Color.white);
        newRequestJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        newRequestJButton.setText("View New Requests");
        newRequestJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRequestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(newRequestJButton)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(newRequestJButton)
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRequestJButtonActionPerformed
        // TODO add your handling code here:
        ViewEPAWorkRequestsJPanel viewEPAWorkRequestsJPanel = new ViewEPAWorkRequestsJPanel(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("viewEPAWorkRequestsJPanel", viewEPAWorkRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_newRequestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newRequestJButton;
    // End of variables declaration//GEN-END:variables
}
